"""round_t_models_sync

Revision ID: 5d59c7faa3b9
Revises: s_emart_promo
Create Date: 2026-05-27 04:46:48.647221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d59c7faa3b9'
down_revision: Union[str, Sequence[str], None] = 's_emart_promo'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('request_id', sa.String(length=50), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_audit_timestamp', 'audit_logs', ['timestamp'], unique=False)
    op.create_index('ix_audit_user', 'audit_logs', ['user_id'], unique=False)
    op.create_table('category_corrections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_name_pattern', sa.String(length=500), nullable=False),
    sa.Column('wrong_category_id', sa.String(length=100), nullable=True),
    sa.Column('correct_category_id', sa.String(length=100), nullable=False),
    sa.Column('tokens', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gov_wholesale_prices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_name', sa.String(length=100), nullable=False),
    sa.Column('category_code', sa.String(length=50), nullable=True),
    sa.Column('wholesale_market', sa.String(length=100), nullable=False),
    sa.Column('source', sa.Enum('GARAK_WHOLESALE', 'GANGSEO_WHOLESALE', 'SEOUL_WHOLESALE', 'MAFRA_WHOLESALE', name='govwholesalesource'), nullable=False),
    sa.Column('api_dataset_code', sa.String(length=50), nullable=True),
    sa.Column('unit', sa.String(length=30), nullable=False),
    sa.Column('avg_price', sa.Float(), nullable=False),
    sa.Column('min_price', sa.Float(), nullable=True),
    sa.Column('max_price', sa.Float(), nullable=True),
    sa.Column('upper_bound_rate', sa.Float(), nullable=False),
    sa.Column('lower_bound_rate', sa.Float(), nullable=False),
    sa.Column('hotdeal_rate', sa.Float(), nullable=False),
    sa.Column('recorded_date', sa.DateTime(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_gov_wholesale_market', 'gov_wholesale_prices', ['wholesale_market'], unique=False)
    op.create_index('ix_gov_wholesale_product_date', 'gov_wholesale_prices', ['product_name', 'recorded_date'], unique=False)
    op.create_index('ix_gov_wholesale_source', 'gov_wholesale_prices', ['source'], unique=False)
    op.create_table('hotdeal_comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hotdeal_id', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hotdeal_comments_hotdeal_id'), 'hotdeal_comments', ['hotdeal_id'], unique=False)
    op.create_table('hotdeal_votes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hotdeal_id', sa.Integer(), nullable=False),
    sa.Column('vote_type', sa.String(length=10), nullable=False),
    sa.Column('client_ip', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hotdeal_id', 'client_ip', name='uq_hotdeal_vote_identity')
    )
    op.create_index('ix_hotdeal_votes_deal_type', 'hotdeal_votes', ['hotdeal_id', 'vote_type'], unique=False)
    op.create_index(op.f('ix_hotdeal_votes_hotdeal_id'), 'hotdeal_votes', ['hotdeal_id'], unique=False)
    op.create_table('normalized_week_buckets',
    sa.Column('public_week_bucket_id', sa.String(length=120), nullable=False),
    sa.Column('week_start', sa.DateTime(), nullable=False),
    sa.Column('week_end', sa.DateTime(), nullable=False),
    sa.Column('projection_version', sa.String(length=40), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('public_week_bucket_id'),
    sa.UniqueConstraint('week_start', 'week_end', name='uq_norm_week_range')
    )
    op.create_index('ix_norm_week_start', 'normalized_week_buckets', ['week_start'], unique=False)
    op.create_table('pending_ingestions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('crawler_name', sa.String(length=100), nullable=False),
    sa.Column('crawl_status', sa.String(length=20), nullable=False),
    sa.Column('strategy_used', sa.String(length=50), nullable=True),
    sa.Column('items_count', sa.Integer(), nullable=False),
    sa.Column('items_json', sa.Text(), nullable=False),
    sa.Column('schema_type', sa.String(length=50), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('quality_details', sa.JSON(), nullable=True),
    sa.Column('errors_json', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'CRAWLER_APPROVED', 'APPROVED', 'REJECTED', 'PARTIAL', name='ingestionstatus'), nullable=False),
    sa.Column('crawler_reviewer_notes', sa.Text(), nullable=True),
    sa.Column('db_reviewer_notes', sa.Text(), nullable=True),
    sa.Column('approved_items_json', sa.Text(), nullable=True),
    sa.Column('rejected_reason', sa.Text(), nullable=True),
    sa.Column('crawled_at', sa.DateTime(), nullable=False),
    sa.Column('crawler_reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('db_reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pending_crawled_at', 'pending_ingestions', ['crawled_at'], unique=False)
    op.create_index('ix_pending_crawler', 'pending_ingestions', ['crawler_name'], unique=False)
    op.create_index('ix_pending_status', 'pending_ingestions', ['status'], unique=False)
    op.create_table('normalized_canonical_products',
    sa.Column('public_product_id', sa.String(length=120), nullable=False),
    sa.Column('category_id', sa.String(length=100), nullable=True),
    sa.Column('canonical_name', sa.String(length=255), nullable=False),
    sa.Column('brand', sa.String(length=120), nullable=True),
    sa.Column('aliases', sa.JSON(), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('primary_image_url', sa.String(length=1000), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('projection_version', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('public_product_id')
    )
    op.create_index('ix_norm_product_category', 'normalized_canonical_products', ['category_id'], unique=False)
    op.create_index('ix_norm_product_name', 'normalized_canonical_products', ['canonical_name'], unique=False)
    op.create_table('user_activities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.String(length=30), nullable=False),
    sa.Column('target_type', sa.String(length=30), nullable=True),
    sa.Column('target_id', sa.String(length=100), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_activity_user_type_date', 'user_activities', ['user_id', 'activity_type', 'created_at'], unique=False)
    op.create_table('cart_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('item_name', sa.String(length=300), nullable=False),
    sa.Column('item_price', sa.Float(), nullable=False),
    sa.Column('item_image_url', sa.String(length=500), nullable=True),
    sa.Column('store_name', sa.String(length=100), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('original_price', sa.Float(), nullable=True),
    sa.Column('discount_rate', sa.Float(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'product_id', 'store_name', name='uq_cart_user_product_store')
    )
    op.create_index('ix_cart_user', 'cart_items', ['user_id'], unique=False)
    op.create_table('normalized_product_variants',
    sa.Column('public_variant_id', sa.String(length=120), nullable=False),
    sa.Column('public_product_id', sa.String(length=120), nullable=False),
    sa.Column('variant_name', sa.String(length=255), nullable=False),
    sa.Column('package_quantity', sa.Float(), nullable=True),
    sa.Column('package_unit', sa.String(length=40), nullable=True),
    sa.Column('display_unit', sa.String(length=80), nullable=True),
    sa.Column('bundle_count', sa.Integer(), nullable=False),
    sa.Column('standard_unit', sa.String(length=40), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('projection_version', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['public_product_id'], ['normalized_canonical_products.public_product_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('public_variant_id')
    )
    op.create_index('ix_norm_variant_package', 'normalized_product_variants', ['package_quantity', 'package_unit', 'bundle_count'], unique=False)
    op.create_index('ix_norm_variant_product', 'normalized_product_variants', ['public_product_id'], unique=False)
    op.create_table('pending_categorizations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('suggested_category_id', sa.String(length=100), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('candidates_json', sa.JSON(), nullable=True),
    sa.Column('parsed_keywords', sa.JSON(), nullable=True),
    sa.Column('parsed_attributes', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('admin_category_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pending_cat_product', 'pending_categorizations', ['product_id'], unique=False)
    op.create_index('ix_pending_cat_status', 'pending_categorizations', ['status'], unique=False)
    op.create_table('product_keywords',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('keyword_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'keyword_id', name='uq_product_keyword')
    )
    op.create_index('ix_product_keywords_keyword', 'product_keywords', ['keyword_id'], unique=False)
    op.create_index('ix_product_keywords_product', 'product_keywords', ['product_id'], unique=False)
    op.create_table('product_matches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('mart_name', sa.String(length=50), nullable=False),
    sa.Column('mart_product_id', sa.String(length=200), nullable=True),
    sa.Column('mart_product_name', sa.String(length=300), nullable=True),
    sa.Column('mart_unit', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('match_method', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'mart_name', name='uq_product_mart')
    )
    op.create_index('ix_product_match_active', 'product_matches', ['is_active'], unique=False)
    op.create_index('ix_product_match_mart', 'product_matches', ['mart_name'], unique=False)
    op.create_index('ix_product_match_product', 'product_matches', ['product_id'], unique=False)
    op.create_table('wishlist_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('item_name', sa.String(length=300), nullable=False),
    sa.Column('target_price', sa.Float(), nullable=True),
    sa.Column('item_image_url', sa.String(length=500), nullable=True),
    sa.Column('store_name', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('price_at_add', sa.Float(), nullable=True),
    sa.Column('current_price', sa.Float(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.Column('notify_on_drop', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_wishlist_user', 'wishlist_items', ['user_id'], unique=False)
    op.create_table('normalized_source_listings',
    sa.Column('public_source_listing_id', sa.String(length=120), nullable=False),
    sa.Column('public_variant_id', sa.String(length=120), nullable=False),
    sa.Column('source_name', sa.String(length=120), nullable=False),
    sa.Column('source_record_key', sa.String(length=200), nullable=True),
    sa.Column('source_title', sa.String(length=500), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('image_url', sa.String(length=1000), nullable=True),
    sa.Column('source_unit_text', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('projection_version', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['public_variant_id'], ['normalized_product_variants.public_variant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('public_source_listing_id')
    )
    op.create_index('ix_norm_listing_source', 'normalized_source_listings', ['source_name', 'source_record_key'], unique=False)
    op.create_index('ix_norm_listing_variant', 'normalized_source_listings', ['public_variant_id'], unique=False)
    op.create_table('normalized_offer_events',
    sa.Column('public_offer_event_id', sa.String(length=120), nullable=False),
    sa.Column('public_source_listing_id', sa.String(length=120), nullable=False),
    sa.Column('price_state', sa.String(length=40), nullable=False),
    sa.Column('promotion_type', sa.String(length=40), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('original_price', sa.Float(), nullable=True),
    sa.Column('discount_rate', sa.Float(), nullable=True),
    sa.Column('event_name', sa.String(length=255), nullable=True),
    sa.Column('standard_unit_price', sa.Float(), nullable=True),
    sa.Column('price_per_100g', sa.Float(), nullable=True),
    sa.Column('valid_from', sa.DateTime(), nullable=True),
    sa.Column('valid_to', sa.DateTime(), nullable=True),
    sa.Column('raw_record_id', sa.String(length=200), nullable=True),
    sa.Column('raw_evidence', sa.JSON(), nullable=False),
    sa.Column('audit_provenance', sa.JSON(), nullable=False),
    sa.Column('crawled_at', sa.DateTime(), nullable=False),
    sa.Column('offer_state', sa.String(length=40), nullable=False),
    sa.Column('projection_version', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['public_source_listing_id'], ['normalized_source_listings.public_source_listing_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('public_offer_event_id')
    )
    op.create_index('ix_norm_offer_listing', 'normalized_offer_events', ['public_source_listing_id'], unique=False)
    op.create_index('ix_norm_offer_state', 'normalized_offer_events', ['offer_state'], unique=False)
    op.create_table('normalized_offer_week_links',
    sa.Column('public_offer_event_id', sa.String(length=120), nullable=False),
    sa.Column('public_week_bucket_id', sa.String(length=120), nullable=False),
    sa.Column('observed_min_price', sa.Float(), nullable=True),
    sa.Column('observed_max_price', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['public_offer_event_id'], ['normalized_offer_events.public_offer_event_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['public_week_bucket_id'], ['normalized_week_buckets.public_week_bucket_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('public_offer_event_id', 'public_week_bucket_id')
    )
    op.create_index('ix_norm_offer_week', 'normalized_offer_week_links', ['public_week_bucket_id'], unique=False)
    op.create_index('ix_baseline_product_source', 'baseline_prices', ['product_id', 'source'], unique=False)
    # Round T fix: skip ALTER COLUMN/index reshuffling (SQLite does not support ALTER COLUMN).
    # Only the column additions below are required for API endpoints to function.
    op.add_column('posts', sa.Column('tags', sa.JSON(), nullable=True))
    op.add_column('products', sa.Column('source_type', sa.String(length=20), nullable=True))
    op.add_column('products', sa.Column('categorization_confidence', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('categorization_method', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('profile_image', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('preferences', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    raise NotImplementedError("Round T sync migration is forward-only.")