const fs=require('fs'),path=require('path');
const p1='E:\\pdf\\capston01\\walletSavior\\.github\\workflows';
const p2='E:\\pdf\\capston01\\walletSavior\\.github\\ISSUE_TEMPLATE';
fs.mkdirSync(p1,{recursive:true});
fs.mkdirSync(p2,{recursive:true});
console.log('Created directories');
console.log('\n=== .github contents ===');
fs.readdirSync('E:\\pdf\\capston01\\walletSavior\\.github').forEach(i=>console.log(i));
console.log('\n=== workflows ===');
const w=fs.readdirSync(p1);
console.log(w.length?w.join('\n'):'(empty)');
console.log('\n=== ISSUE_TEMPLATE ===');
const t=fs.readdirSync(p2);
console.log(t.length?t.join('\n'):'(empty)');
