"""
WalletSavior 카테고리/키워드 데이터 입출력.

JSON export/import, DB seed SQL 생성, 병합 기능.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Optional

from .categories import CATEGORIES, get_category_tree, validate_tree
from .keywords import KEYWORDS


# ──────────────────────────────────────────────
# JSON Export
# ──────────────────────────────────────────────

def export_categories_json(filepath: Optional[str] = None) -> str:
    """
    전체 카테고리를 JSON 으로 내보내기.

    filepath 를 지정하면 파일로 저장, 아니면 JSON 문자열 반환.
    """
    tree = get_category_tree()
    data = {"categories": tree, "total_count": len(CATEGORIES)}
    json_str = json.dumps(data, ensure_ascii=False, indent=2)

    if filepath:
        Path(filepath).write_text(json_str, encoding="utf-8")

    return json_str


def export_categories_flat_json(filepath: Optional[str] = None) -> str:
    """카테고리를 flat 리스트 JSON 으로 내보내기."""
    data = {"categories": CATEGORIES, "total_count": len(CATEGORIES)}
    json_str = json.dumps(data, ensure_ascii=False, indent=2)

    if filepath:
        Path(filepath).write_text(json_str, encoding="utf-8")

    return json_str


def export_keywords_json(filepath: Optional[str] = None) -> str:
    """키워드를 JSON 으로 내보내기."""
    data = {"keywords": KEYWORDS, "total_count": len(KEYWORDS)}
    json_str = json.dumps(data, ensure_ascii=False, indent=2)

    if filepath:
        Path(filepath).write_text(json_str, encoding="utf-8")

    return json_str


# ──────────────────────────────────────────────
# JSON Import
# ──────────────────────────────────────────────

def import_categories_json(filepath_or_str: str) -> list[dict]:
    """
    JSON 에서 카테고리 가져오기.

    파일 경로 또는 JSON 문자열을 받습니다.
    """
    path = Path(filepath_or_str)
    if path.exists():
        text = path.read_text(encoding="utf-8")
    else:
        text = filepath_or_str

    data = json.loads(text)

    if "categories" in data:
        categories = data["categories"]
    else:
        categories = data

    if isinstance(categories, list):
        return categories
    return []


def import_keywords_json(filepath_or_str: str) -> list[dict]:
    """JSON 에서 키워드 가져오기."""
    path = Path(filepath_or_str)
    if path.exists():
        text = path.read_text(encoding="utf-8")
    else:
        text = filepath_or_str

    data = json.loads(text)

    if "keywords" in data:
        keywords = data["keywords"]
    else:
        keywords = data

    if isinstance(keywords, list):
        return keywords
    return []


# ──────────────────────────────────────────────
# 병합(Merge)
# ──────────────────────────────────────────────

def merge_categories(existing: list[dict], new_categories: list[dict]) -> list[dict]:
    """
    기존 카테고리에 새 카테고리를 병합 (중복 제거).

    - 같은 ID 가 있으면 새 데이터로 업데이트
    - 새 ID 는 추가
    - 기존에만 있는 것은 유지
    """
    idx = {c["id"]: c for c in existing}

    for cat in new_categories:
        idx[cat["id"]] = cat

    result = list(idx.values())
    # parent_id 기준 정렬 (루트 먼저, 그 다음 depth 순)
    result.sort(key=lambda c: (c.get("depth", 0), c.get("sort_order", 0)))
    return result


def merge_keywords(existing: list[dict], new_keywords: list[dict]) -> list[dict]:
    """
    기존 키워드에 새 키워드를 병합 (중복 제거).

    - 같은 word 가 있으면 새 데이터로 업데이트
    - search_count 는 더 큰 값 유지
    """
    idx = {kw["word"]: kw for kw in existing}

    for kw in new_keywords:
        if kw["word"] in idx:
            old = idx[kw["word"]]
            kw["search_count"] = max(
                kw.get("search_count", 0),
                old.get("search_count", 0),
            )
        idx[kw["word"]] = kw

    return list(idx.values())


# ──────────────────────────────────────────────
# SQL Seed 생성
# ──────────────────────────────────────────────

def _escape_sql(value: str) -> str:
    """SQL 값 이스케이프."""
    return value.replace("'", "''")


def generate_seed_sql(
    include_categories: bool = True,
    include_keywords: bool = True,
) -> str:
    """
    카테고리/키워드 INSERT SQL 생성.

    기존 DB 와 충돌 방지를 위해 INSERT OR IGNORE 사용.
    """
    lines: list[str] = [
        "-- WalletSavior Category & Keyword Seed Data",
        "-- Generated by category_data.data_io",
        "",
    ]

    if include_categories:
        # 무결성 검증
        errors = validate_tree()
        if errors:
            lines.append(f"-- WARNING: {len(errors)} validation error(s) found")
            for err in errors:
                lines.append(f"--   {err}")
            lines.append("")

        lines.append("-- Categories")
        lines.append("BEGIN TRANSACTION;")
        for cat in CATEGORIES:
            parent = f"'{_escape_sql(cat['parent_id'])}'" if cat["parent_id"] else "NULL"
            icon = f"'{_escape_sql(cat['icon'])}'" if cat.get("icon") else "NULL"
            attrs = f"'{_escape_sql(json.dumps(cat.get('attributes', {}), ensure_ascii=False))}'" if cat.get("attributes") else "NULL"

            lines.append(
                f"INSERT OR IGNORE INTO categories "
                f"(id, name, parent_id, depth, sort_order, icon, attributes, is_active) "
                f"VALUES ('{_escape_sql(cat['id'])}', '{_escape_sql(cat['name'])}', "
                f"{parent}, {cat['depth']}, {cat['sort_order']}, "
                f"{icon}, {attrs}, 1);"
            )
        lines.append("COMMIT;")
        lines.append("")

    if include_keywords:
        lines.append("-- Keywords")
        lines.append("BEGIN TRANSACTION;")
        for kw in KEYWORDS:
            cat_id = f"'{_escape_sql(kw['category_id'])}'" if kw.get("category_id") else "NULL"
            syns = _escape_sql(json.dumps(kw.get("synonyms", []), ensure_ascii=False))

            lines.append(
                f"INSERT OR IGNORE INTO keywords "
                f"(word, synonyms, category_id, search_count, is_active) "
                f"VALUES ('{_escape_sql(kw['word'])}', '{syns}', "
                f"{cat_id}, {kw.get('search_count', 0)}, 1);"
            )
        lines.append("COMMIT;")
        lines.append("")

    return "\n".join(lines)


def save_seed_sql(filepath: str, **kwargs) -> None:
    """SQL seed 파일 저장."""
    sql = generate_seed_sql(**kwargs)
    Path(filepath).write_text(sql, encoding="utf-8")
